/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.edu.ijse.hpt.ui;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.edu.ijse.hpt.controller.CustomerController;
import lk.edu.ijse.hpt.controller.ItemController;
import lk.edu.ijse.hpt.controller.OrderController;
import lk.edu.ijse.hpt.controllerImpl.CustomerControllerImpl;
import lk.edu.ijse.hpt.controllerImpl.ItemControllerImpl;
import lk.edu.ijse.hpt.controllerImpl.OrderControllerImpl;
import lk.edu.ijse.hpt.dto.CustomerDTO;
import lk.edu.ijse.hpt.dto.ItemDTO;
import lk.edu.ijse.hpt.dto.OrderDetailDTO;
import lk.edu.ijse.hpt.dto.OrdersDTO;
import lk.edu.ijse.hpt.entity.ItemEntity;
import lk.edu.ijse.hpt.entity.OrdersEntity;
import lk.edu.ijse.hpt.service.ItemService;

/**
 *
 * @author Thilini Hansika
 */
public class PlaceOrderForm extends javax.swing.JFrame {

    /**
     * Creates new form PlaceOrderForm
     */
    public PlaceOrderForm() {
        initComponents();
        getAllItems();
        loadSystemDate();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOrderDate = new javax.swing.JTextField();
        txtTotalAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbDescription = new javax.swing.JComboBox<>();
        txtCustomerName = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtQtyOnHand = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Place Order");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 160, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Order Date");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 90, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Total Amount");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 100, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Customer Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 20));
        jPanel1.add(txtOrderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 160, 30));

        txtTotalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAmountActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 150, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Customer Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Description");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Unit Price");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 100, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Qty");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 80, 20));

        cmbDescription.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDescriptionItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 30));
        jPanel1.add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 170, 30));
        jPanel1.add(txtUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, 30));

        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 130, 30));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Unit Price", "Qty", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrder);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 640, 160));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Qyt On Hand");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 100, 20));
        jPanel1.add(txtQtyOnHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 130, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SAVE & PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 170, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAmountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            CustomerController controller = new CustomerControllerImpl();
            CustomerDTO customerDTO = new CustomerDTO();
            customerDTO.setCustomerName(txtCustomerName.getText());

            OrderController oController = new OrderControllerImpl();
           // List<OrdersDTO> orderList = new ArrayList<>();
            OrdersDTO dTO = new OrdersDTO();
            dTO.setOrderdate(txtOrderDate.getText());
            dTO.setCustomerDTO(customerDTO);

           // orderList.add(dTO);
           // customerDTO.setOrderList(orderList);
            DefaultTableModel dtm = (DefaultTableModel) tblOrder.getModel();
            ItemController itemController = new ItemControllerImpl();
            List<OrderDetailDTO> detailList = new ArrayList<>();
            for (int i = 0; i < dtm.getRowCount(); i++) {
                ItemDTO item = itemController.searchByNAme((String) dtm.getValueAt(i, 0));
                item.setQtyOnHand(item.getQtyOnHand() - Integer.parseInt(dtm.getValueAt(i, 2).toString()));
                OrderDetailDTO od = new OrderDetailDTO();
                od.setItemDTO(item);
                od.setOrdersDTO(dTO);
                od.setQty(Integer.parseInt(dtm.getValueAt(i, 2).toString()));
                od.setUnitPrice(Double.parseDouble(dtm.getValueAt(i, 1).toString()));
                detailList.add(od);
            }
            dTO.setOrderList(detailList);
             controller.addCustomer(customerDTO);
         boolean adOrder=   oController.addOrder(dTO);
         if(adOrder){
             JOptionPane.showMessageDialog(this, "Added");
         }else{
             JOptionPane.showMessageDialog(this, "Error");
         }
            
        } catch (Exception ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
      

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbDescriptionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDescriptionItemStateChanged
        ItemController ic = new ItemControllerImpl();
        if (cmbDescription.getSelectedIndex() != -1) {
            try {
                String itmDes = (String) cmbDescription.getSelectedItem();
                ItemDTO item = ic.searchByNAme((String) cmbDescription.getSelectedItem());
                txtUnitPrice.setText(Double.toString(item.getUnitPrice()));
                txtQtyOnHand.setText(Integer.toString(item.getQtyOnHand()));

            } catch (Exception ex) {
                Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmbDescriptionItemStateChanged

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        int x = Integer.parseInt(txtQty.getText());
        int qtyOnHAnd = Integer.parseInt(txtQtyOnHand.getText()) - x;
        if (qtyOnHAnd >= 0) {
            txtQtyOnHand.setText(Integer.toString(qtyOnHAnd));
            Double amount = x * Double.parseDouble(txtUnitPrice.getText());
            if (cmbDescription.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Item Not Selected");
            } else {
                DefaultTableModel dtm = (DefaultTableModel) tblOrder.getModel();

                Object[] rowdata = {cmbDescription.getSelectedItem(), txtUnitPrice.getText(), x, amount};
                dtm.addRow(rowdata);
                setTotle();
            }
        }

    }//GEN-LAST:event_txtQtyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDescription;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtOrderDate;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtQtyOnHand;
    private javax.swing.JTextField txtTotalAmount;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
public void getAllItems() {
        try {
            ItemController itemController = new ItemControllerImpl();

            List<ItemDTO> lis = itemController.getAllItems();
            for (ItemDTO li : lis) {
                cmbDescription.addItem(li.getDescription());
            }
        } catch (Exception ex) {
            Logger.getLogger(PlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadSystemDate() {
        Date d1 = new Date(); //Current System date
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formatDate = df.format(d1);
        txtOrderDate.setText(formatDate);

    }

    private void setTotle() {
        DefaultTableModel dtm = (DefaultTableModel) tblOrder.getModel();
        double total = 0;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            total += Double.parseDouble(dtm.getValueAt(i, 3).toString());
        }
        txtTotalAmount.setText(Double.toString(total));
    }
}
